### ISSUE TITLE
Can you offer support to port this to STM32L432?

### ISSUE THREAD

**Issue by DeflateAwning** [sq8vps/vp-digi#19]
In order to be compatible with the hardware and microcontroller used for the [NucleoTNC project](https://github.com/mobilinkd/NucleoTNC), it would be awesome if there was support for that microcontroller on this project. Any advice on how best to get that support?

**Comment by sq8vps** [comment]
It is absolutely possible to port VP-Digi to other MCUs. Right now I am refactoring/rewriting the firmware, so it should be easier to port in the future. I will let you know as soon as I finish.

**Comment by DeflateAwning** [comment]
Thank you!
