### ISSUE TITLE
Build error: `multiple definition of 'ax25Cfg'`

### ISSUE THREAD

**Issue by DeflateAwning** [sq8vps/vp-digi#20]
I'm getting the following build error after converting to STM32CubeIDE v1.13.0:

```
C:/ST/STM32CubeIDE_1.13/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.11.3.rel1.win32_1.1.0.202305231506/tools/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld.exe: ./Src/beacon.o:C:/Users/me/vp-digi/Debug/../Inc/ax25.h:45: multiple definition of `ax25Cfg'; ./Src/ax25.o:C:/Users/me/vp-digi/Debug/../Inc/ax25.h:45: first defined here
```

Any idea what's going on? 

I'm curious why those variables are declared in the headers and not in the C files (and then declared as `extern`s)?

**Comment by sq8vps** [comment]
There compiler is probably different and it does not allow such things. I am refactoring the code to get rid of these bugs
