### ISSUE TITLE
Wrong date in changelog for latest release

### ISSUE THREAD

**Issue by DeflateAwning** [sq8vps/vp-digi#21]
1. In the changelog, you have a `2023-08-29` for the latest release (which is in the future). Looking at the commit history, I think you mean July 29 (`2023-07-29`).
2. It would be awesome if you tagged release versions with GitHub releases, and added the compiled hex files there for each release (standard practice for this sort of project).

**Comment by sq8vps** [comment]
Ad. 1. Thanks for spotting, the date is now corrected.
Ad. 2. I will try to add it tomorrow.

**Comment by sq8vps** [comment]
Done.
