### ISSUE TITLE
manual : UART terminal settings

### ISSUE THREAD

**Issue by ch0mik** [sq8vps/vp-digi#39]
Cześć

w manualu warto zaznaczyć jakie mają był ustawienia do połączenia się via UART/USB. Brakuje np. 
1) domyślny bitrate / ustawienia parzystości itp np. w putty
2) do tej pory nie wiem jak obsługuje backspace

dziękuje wielkie za taki projekt!

Vy 73! de SQ7MRU

**Comment by sq8vps** [comment]
Dodałem informacje do dokumentacji.
Domyślne ustawienia UART to 9600 Bd, 8 bitów danych, 1 bit stopu, brak bitów parzystości.
Backspace powinno być kodowane jako Control+H, czyli standardowe ASCII 8.
